// GENERATED by kkpc/tools/gen_kong_anims_rs.py from kong_actions.json -- do not edit by hand.
//! Kong action table recovered from the level stream (ff00018c.dec): action records at 0x8d78fb, kit u32[371] at 0x8d706a,
//! TRL event tracks at 0x8dcafb. All values here are data [C] read from the game files (see spec/evidence/KC01.md section "Action records").


/// Sentinel for "no event" in the u16 frame fields.
pub const NONE: u16 = 0xffff;

/// One item of an action record (19 file bytes; `b2` speed, `b3` mask [L]).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Item {
    /// clip length in clip frames (60 Hz at speed byte 64)
    pub frames: u16,
    /// item byte b2: playback speed = speed / 64 (`ANIM_GetBaseSpeed@0x4244e0`; clip fps = b2 * 60 / 64, `fn@0x00946040`)
    pub speed: u8,
    /// item byte b3 (semantics not recovered)
    pub b3: u8,
    /// first frame at which a TRL event sets object flag 0x1 (`k_exec_hit_window_open@0x887490` tests it); NONE if the clip never opens it
    pub hit_start: u16,
    /// first frame at which a TRL event sets flag 0x100 (`fn@0x00884780`: the cancel window); NONE if never
    pub cancel: u16,
    /// all `Obj_ModifyFlags` set-mask events of the clip: (frame, mask)
    pub flags: &'static [(u16, u16)],
}

impl Item {
    /// Length in 60 Hz game frames (speed applied).
    pub fn len60(&self) -> f32 {
        self.frames as f32 * 64.0 / self.speed.max(1) as f32
    }
}

/// An action record: items play in sequence; `loop_from` 255 = the last item ends the action, else the item index it loops back to.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Action {
    pub id: u16,
    pub loop_from: u8,
    pub items: &'static [Item],
}

impl Action {
    pub fn looping(&self) -> bool {
        self.loop_from != 255
    }
    /// Total length of one pass in 60 Hz game frames.
    pub fn len60(&self) -> f32 {
        self.items.iter().map(|i| i.len60()).sum()
    }
    /// Offset (60 Hz frames) at which item `k` starts.
    pub fn item_start60(&self, k: usize) -> f32 {
        self.items.iter().take(k).map(|i| i.len60()).sum()
    }
    /// First hit-window opening (flag 0x1), in 60 Hz frames from the action start.
    pub fn hit_start60(&self) -> Option<f32> {
        let mut t = 0.0;
        for i in self.items {
            if i.hit_start != NONE {
                return Some(t + i.hit_start as f32 * 64.0 / i.speed.max(1) as f32);
            }
            t += i.len60();
        }
        None
    }
    /// First cancel-window opening (flag 0x100), in 60 Hz frames from the action start.
    pub fn cancel60(&self) -> Option<f32> {
        let mut t = 0.0;
        for i in self.items {
            if i.cancel != NONE {
                return Some(t + i.cancel as f32 * 64.0 / i.speed.max(1) as f32);
            }
            t += i.len60();
        }
        None
    }
}

pub fn action(id: u32) -> Option<&'static Action> {
    ACTIONS.binary_search_by_key(&(id as u16), |a| a.id).ok().map(|i| &ACTIONS[i])
}

/// Blend byte of the transition entry that `fn@0x00946a30` finds when action `from` (item `item`) switches to action `to` [L: unit = frames].
pub fn blend(from: u32, item: u8, to: u32) -> Option<u8> {
    TRANSITIONS.iter().find(|t| t.0 as u32 == from && t.1 == item && t.2 as u32 == to).map(|t| t.4)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_and_complete() {
        assert_eq!(ACTIONS.len(), 253);
        assert!(ACTIONS.windows(2).all(|w| w[0].id < w[1].id));
    }

    #[test]
    fn attack_clips_pin_the_recovered_event_frames() {
        // (id, clip frames, first frame that sets flag 0x1)
        for (id, frames, hit) in [(0x17, 51, 44), (0x19, 52, 43), (0x1b, 56, 39), (0x1d, 56, 45), (0x1f, 63, 40), (0x16, 36, 24)] {
            let a = action(id).unwrap();
            assert_eq!(a.items.len(), 1);
            assert_eq!(a.items[0].frames, frames, "{id:#x}");
            assert_eq!(a.items[0].speed, 64);
            assert_eq!(a.items[0].hit_start, hit, "{id:#x}");
            assert!(!a.looping());
        }
        // the recovery clips after the punches / phase 2
        for (id, frames) in [(0x18, 22), (0x1a, 22), (0x1c, 41), (0x1e, 29)] {
            assert_eq!(action(id).unwrap().items[0].frames, frames);
        }
    }

    #[test]
    fn cancel_window_is_a_clip_end_event() {
        // jump 6/7 (65 f), roll 0xe (50 f): the 0x1e0 window opens on the last frame
        assert_eq!(action(0xe).unwrap().cancel60(), Some(50.0));
        assert_eq!(action(6).unwrap().cancel60(), Some(65.0));
        // chest pound: the event is at frame 148 of a 144 frame clip, so the window is never open inside the clip
        let p = action(0xab).unwrap();
        assert_eq!(p.items[0].frames, 144);
        assert_eq!(p.items[0].cancel, 148);
        // repel is two items (22 f + 36 f); its second item opens the windows at frame 7 and 36
        let r = action(0xac).unwrap();
        assert_eq!(r.items.len(), 2);
        assert_eq!((r.items[0].frames, r.items[1].frames), (22, 36));
        assert_eq!(r.len60(), 58.0);
        assert_eq!(r.hit_start60(), Some(22.0));
        // plain punches never open the cancel window: only the end of the clip chains
        assert_eq!(action(0x17).unwrap().cancel60(), None);
    }

    #[test]
    fn speeds_and_loops() {
        assert!(action(0).unwrap().looping() && action(0).unwrap().loop_from == 0);
        // walk is played at 2x (speed byte 128) over 96 clip frames = 48 game frames
        assert_eq!(action(0xa).unwrap().items[0].speed, 128);
        assert_eq!(action(0xa).unwrap().len60(), 48.0);
        // held-object swings are slowed to 50/64
        assert_eq!(action(0xc2).unwrap().items[0].speed, 50);
        assert!((action(0xc2).unwrap().len60() - 46.0 * 64.0 / 50.0).abs() < 1e-3);
        assert!(!action(0x17).unwrap().looping());
    }

    #[test]
    fn blend_table() {
        // idle (action 0) -> walk/run/... entries carry blend bytes; 0 -> 0xc is 10, 0 -> 0 is 30 frames
        assert_eq!(blend(0, 0, 0xc), Some(10));
        assert_eq!(blend(0, 0, 0), Some(30));
        assert_eq!(blend(0x17, 0, 0x18).is_some(), TRANSITIONS.iter().any(|t| t.0 == 0x17 && t.2 == 0x18));
    }
}

pub static ACTIONS: &[Action] = &[
    Action { id: 0x0, loop_from: 0, items: &[Item { frames: 121, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x1, loop_from: 255, items: &[Item { frames: 121, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x2, loop_from: 255, items: &[Item { frames: 47, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x3, loop_from: 1, items: &[Item { frames: 198, speed: 64, b3: 228, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 90, speed: 64, b3: 228, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x4, loop_from: 255, items: &[Item { frames: 57, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 38, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x5, loop_from: 255, items: &[Item { frames: 21, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 53, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x6, loop_from: 255, items: &[Item { frames: 65, speed: 64, b3: 252, hit_start: NONE, cancel: 65, flags: &[(65, 0x1e0)] }] },
    Action { id: 0x7, loop_from: 255, items: &[Item { frames: 65, speed: 64, b3: 252, hit_start: NONE, cancel: 65, flags: &[(65, 0x1e0)] }] },
    Action { id: 0x8, loop_from: 1, items: &[Item { frames: 40, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 160, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 83, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 160, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 153, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xa, loop_from: 0, items: &[Item { frames: 96, speed: 128, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xb, loop_from: 0, items: &[Item { frames: 96, speed: 128, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xc, loop_from: 0, items: &[Item { frames: 62, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd, loop_from: 0, items: &[Item { frames: 62, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xe, loop_from: 255, items: &[Item { frames: 50, speed: 64, b3: 0, hit_start: NONE, cancel: 50, flags: &[(50, 0x1e0)] }] },
    Action { id: 0xf, loop_from: 255, items: &[Item { frames: 64, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x10, loop_from: 0, items: &[Item { frames: 43, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x11, loop_from: 0, items: &[Item { frames: 43, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x12, loop_from: 0, items: &[Item { frames: 26, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x13, loop_from: 0, items: &[Item { frames: 26, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x14, loop_from: 255, items: &[Item { frames: 50, speed: 64, b3: 0, hit_start: NONE, cancel: 50, flags: &[(50, 0x1e0)] }] },
    Action { id: 0x15, loop_from: 255, items: &[Item { frames: 27, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x16, loop_from: 255, items: &[Item { frames: 36, speed: 64, b3: 240, hit_start: 24, cancel: NONE, flags: &[(24, 0x1)] }] },
    Action { id: 0x17, loop_from: 255, items: &[Item { frames: 51, speed: 64, b3: 4, hit_start: 44, cancel: NONE, flags: &[(44, 0x1)] }] },
    Action { id: 0x18, loop_from: 255, items: &[Item { frames: 22, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x19, loop_from: 255, items: &[Item { frames: 52, speed: 64, b3: 4, hit_start: 43, cancel: NONE, flags: &[(43, 0x1)] }] },
    Action { id: 0x1a, loop_from: 255, items: &[Item { frames: 22, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x1b, loop_from: 255, items: &[Item { frames: 56, speed: 64, b3: 4, hit_start: 39, cancel: NONE, flags: &[(39, 0x1), (56, 0xe0)] }] },
    Action { id: 0x1c, loop_from: 255, items: &[Item { frames: 41, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x1d, loop_from: 255, items: &[Item { frames: 56, speed: 64, b3: 4, hit_start: 45, cancel: NONE, flags: &[(45, 0x1), (65, 0xe0)] }] },
    Action { id: 0x1e, loop_from: 255, items: &[Item { frames: 29, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x1f, loop_from: 255, items: &[Item { frames: 63, speed: 64, b3: 4, hit_start: 40, cancel: NONE, flags: &[(40, 0x1)] }] },
    Action { id: 0x21, loop_from: 255, items: &[Item { frames: 93, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x22, loop_from: 255, items: &[Item { frames: 85, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x23, loop_from: 255, items: &[Item { frames: 44, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x24, loop_from: 255, items: &[Item { frames: 71, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x25, loop_from: 255, items: &[Item { frames: 71, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x27, loop_from: 255, items: &[Item { frames: 24, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x28, loop_from: 255, items: &[Item { frames: 51, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 21, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x29, loop_from: 255, items: &[Item { frames: 39, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 22, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x2a, loop_from: 255, items: &[Item { frames: 41, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 21, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x2b, loop_from: 255, items: &[Item { frames: 41, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 29, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x2c, loop_from: 255, items: &[Item { frames: 43, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 62, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x2d, loop_from: 255, items: &[Item { frames: 82, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 62, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x2e, loop_from: 255, items: &[Item { frames: 56, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 62, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x2f, loop_from: 255, items: &[Item { frames: 56, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 62, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x30, loop_from: 255, items: &[Item { frames: 76, speed: 64, b3: 48, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x31, loop_from: 255, items: &[Item { frames: 73, speed: 64, b3: 48, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x32, loop_from: 255, items: &[Item { frames: 28, speed: 64, b3: 241, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x33, loop_from: 255, items: &[Item { frames: 28, speed: 64, b3: 241, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x34, loop_from: 255, items: &[Item { frames: 57, speed: 64, b3: 241, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x35, loop_from: 255, items: &[Item { frames: 60, speed: 64, b3: 241, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x36, loop_from: 255, items: &[Item { frames: 60, speed: 64, b3: 240, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x37, loop_from: 255, items: &[Item { frames: 60, speed: 64, b3: 240, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x38, loop_from: 1, items: &[Item { frames: 45, speed: 128, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 63, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 12, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x39, loop_from: 255, items: &[Item { frames: 24, speed: 64, b3: 2, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x3a, loop_from: 255, items: &[Item { frames: 33, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x3b, loop_from: 255, items: &[Item { frames: 60, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x3c, loop_from: 255, items: &[Item { frames: 28, speed: 56, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x3d, loop_from: 255, items: &[Item { frames: 63, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x3e, loop_from: 2, items: &[Item { frames: 67, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 63, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x3f, loop_from: 255, items: &[Item { frames: 51, speed: 64, b3: 0, hit_start: NONE, cancel: 7, flags: &[(7, 0x100)] }] },
    Action { id: 0x40, loop_from: 1, items: &[Item { frames: 40, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 11, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x41, loop_from: 255, items: &[Item { frames: 30, speed: 32, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x42, loop_from: 255, items: &[Item { frames: 114, speed: 64, b3: 1, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x43, loop_from: 255, items: &[Item { frames: 38, speed: 64, b3: 1, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x44, loop_from: 255, items: &[Item { frames: 59, speed: 64, b3: 1, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x45, loop_from: 255, items: &[Item { frames: 73, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x46, loop_from: 0, items: &[Item { frames: 12, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x47, loop_from: 0, items: &[Item { frames: 12, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x48, loop_from: 255, items: &[Item { frames: 41, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x49, loop_from: 255, items: &[Item { frames: 57, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x4a, loop_from: 255, items: &[Item { frames: 57, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x4b, loop_from: 0, items: &[Item { frames: 48, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x4c, loop_from: 0, items: &[Item { frames: 58, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x4d, loop_from: 0, items: &[Item { frames: 62, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x4e, loop_from: 255, items: &[Item { frames: 21, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x4f, loop_from: 0, items: &[Item { frames: 10, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x50, loop_from: 255, items: &[Item { frames: 20, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x51, loop_from: 0, items: &[Item { frames: 10, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x52, loop_from: 255, items: &[Item { frames: 32, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x53, loop_from: 0, items: &[Item { frames: 10, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x54, loop_from: 255, items: &[Item { frames: 32, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x55, loop_from: 0, items: &[Item { frames: 19, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x56, loop_from: 255, items: &[Item { frames: 20, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x57, loop_from: 0, items: &[Item { frames: 11, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x58, loop_from: 255, items: &[Item { frames: 29, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x59, loop_from: 0, items: &[Item { frames: 11, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x5a, loop_from: 255, items: &[Item { frames: 29, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x5b, loop_from: 0, items: &[Item { frames: 11, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x5c, loop_from: 255, items: &[Item { frames: 21, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x5d, loop_from: 255, items: &[Item { frames: 10, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x5e, loop_from: 255, items: &[Item { frames: 39, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 19, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x5f, loop_from: 1, items: &[Item { frames: 17, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 11, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x60, loop_from: 255, items: &[Item { frames: 15, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x61, loop_from: 255, items: &[Item { frames: 39, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x62, loop_from: 255, items: &[Item { frames: 19, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x63, loop_from: 255, items: &[Item { frames: 22, speed: 64, b3: 9, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x64, loop_from: 0, items: &[Item { frames: 150, speed: 64, b3: 24, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x65, loop_from: 0, items: &[Item { frames: 112, speed: 64, b3: 24, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x66, loop_from: 0, items: &[Item { frames: 112, speed: 64, b3: 24, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x67, loop_from: 0, items: &[Item { frames: 112, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x68, loop_from: 0, items: &[Item { frames: 112, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x6b, loop_from: 255, items: &[Item { frames: 47, speed: 64, b3: 1, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 39, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x6c, loop_from: 255, items: &[Item { frames: 47, speed: 64, b3: 1, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 33, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x6e, loop_from: 255, items: &[Item { frames: 124, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x6f, loop_from: 255, items: &[Item { frames: 76, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x70, loop_from: 255, items: &[Item { frames: 81, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x71, loop_from: 255, items: &[Item { frames: 75, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x72, loop_from: 255, items: &[Item { frames: 76, speed: 64, b3: 244, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x80, loop_from: 255, items: &[Item { frames: 49, speed: 64, b3: 0, hit_start: 22, cancel: NONE, flags: &[(22, 0x29)] }] },
    Action { id: 0x81, loop_from: 255, items: &[Item { frames: 46, speed: 64, b3: 0, hit_start: 28, cancel: NONE, flags: &[(28, 0x1)] }] },
    Action { id: 0x82, loop_from: 0, items: &[Item { frames: 39, speed: 55, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x83, loop_from: 0, items: &[Item { frames: 39, speed: 55, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x84, loop_from: 0, items: &[Item { frames: 54, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x85, loop_from: 0, items: &[Item { frames: 64, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x86, loop_from: 255, items: &[Item { frames: 22, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x87, loop_from: 255, items: &[Item { frames: 22, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x88, loop_from: 0, items: &[Item { frames: 80, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x89, loop_from: 255, items: &[Item { frames: 67, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x8a, loop_from: 255, items: &[Item { frames: 161, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x8b, loop_from: 255, items: &[Item { frames: 24, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x8c, loop_from: 255, items: &[Item { frames: 23, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x8e, loop_from: 255, items: &[Item { frames: 12, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x8f, loop_from: 255, items: &[Item { frames: 37, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x90, loop_from: 255, items: &[Item { frames: 52, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x91, loop_from: 255, items: &[Item { frames: 64, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x92, loop_from: 255, items: &[Item { frames: 64, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x93, loop_from: 255, items: &[Item { frames: 29, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x94, loop_from: 255, items: &[Item { frames: 29, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x96, loop_from: 255, items: &[Item { frames: 59, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x97, loop_from: 255, items: &[Item { frames: 53, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x98, loop_from: 255, items: &[Item { frames: 16, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 17, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x99, loop_from: 255, items: &[Item { frames: 63, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x9a, loop_from: 255, items: &[Item { frames: 55, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x9b, loop_from: 255, items: &[Item { frames: 64, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x9c, loop_from: 255, items: &[Item { frames: 39, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xa2, loop_from: 255, items: &[Item { frames: 38, speed: 64, b3: 8, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xa4, loop_from: 255, items: &[Item { frames: 54, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xa5, loop_from: 255, items: &[Item { frames: 54, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xa6, loop_from: 255, items: &[Item { frames: 19, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 39, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xa7, loop_from: 255, items: &[Item { frames: 22, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xa8, loop_from: 255, items: &[Item { frames: 67, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 75, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xa9, loop_from: 255, items: &[Item { frames: 45, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xaa, loop_from: 255, items: &[Item { frames: 75, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xab, loop_from: 255, items: &[Item { frames: 144, speed: 64, b3: 192, hit_start: NONE, cancel: 148, flags: &[(148, 0x1e0)] }] },
    Action { id: 0xac, loop_from: 255, items: &[Item { frames: 22, speed: 64, b3: 196, hit_start: 22, cancel: NONE, flags: &[(22, 0xe0), (22, 0x1)] },
        Item { frames: 36, speed: 64, b3: 196, hit_start: 36, cancel: 36, flags: &[(7, 0xe0), (36, 0x1e0), (36, 0x1)] }] },
    Action { id: 0xad, loop_from: 255, items: &[Item { frames: 162, speed: 64, b3: 192, hit_start: NONE, cancel: 162, flags: &[(138, 0xe0), (162, 0x1e0), (168, 0x4000)] }] },
    Action { id: 0xae, loop_from: 255, items: &[Item { frames: 103, speed: 64, b3: 192, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xaf, loop_from: 255, items: &[Item { frames: 103, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xb0, loop_from: 255, items: &[Item { frames: 95, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xb1, loop_from: 255, items: &[Item { frames: 162, speed: 64, b3: 192, hit_start: NONE, cancel: 162, flags: &[(138, 0xe0), (162, 0x1e0), (168, 0x4000)] }] },
    Action { id: 0xb2, loop_from: 255, items: &[Item { frames: 501, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[(266, 0x4000), (502, 0x4000)] },
        Item { frames: 103, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xb3, loop_from: 255, items: &[Item { frames: 44, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xb4, loop_from: 255, items: &[Item { frames: 31, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xb5, loop_from: 255, items: &[Item { frames: 10, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xb6, loop_from: 255, items: &[Item { frames: 10, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xbe, loop_from: 0, items: &[Item { frames: 98, speed: 64, b3: 192, hit_start: NONE, cancel: 98, flags: &[(98, 0x1e0)] }] },
    Action { id: 0xbf, loop_from: 0, items: &[Item { frames: 98, speed: 64, b3: 192, hit_start: NONE, cancel: 98, flags: &[(98, 0x1e0)] }] },
    Action { id: 0xc0, loop_from: 0, items: &[Item { frames: 40, speed: 64, b3: 192, hit_start: NONE, cancel: 41, flags: &[(41, 0x1e0)] }] },
    Action { id: 0xc1, loop_from: 0, items: &[Item { frames: 40, speed: 64, b3: 192, hit_start: NONE, cancel: 40, flags: &[(40, 0x1e0)] }] },
    Action { id: 0xc2, loop_from: 255, items: &[Item { frames: 46, speed: 50, b3: 192, hit_start: 22, cancel: 46, flags: &[(22, 0x1), (35, 0xe0), (46, 0x1e0)] }] },
    Action { id: 0xc3, loop_from: 255, items: &[Item { frames: 24, speed: 64, b3: 192, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xc4, loop_from: 255, items: &[Item { frames: 46, speed: 50, b3: 192, hit_start: 22, cancel: 46, flags: &[(22, 0x1), (35, 0xe0), (46, 0x1e0)] }] },
    Action { id: 0xc5, loop_from: 255, items: &[Item { frames: 24, speed: 64, b3: 192, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xc6, loop_from: 255, items: &[Item { frames: 22, speed: 50, b3: 192, hit_start: 17, cancel: NONE, flags: &[(17, 0x1), (22, 0xe0)] }] },
    Action { id: 0xc7, loop_from: 255, items: &[Item { frames: 30, speed: 64, b3: 192, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xc8, loop_from: 255, items: &[Item { frames: 30, speed: 64, b3: 192, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xc9, loop_from: 255, items: &[Item { frames: 40, speed: 64, b3: 192, hit_start: NONE, cancel: 40, flags: &[(40, 0x1e0)] }] },
    Action { id: 0xca, loop_from: 255, items: &[Item { frames: 40, speed: 64, b3: 192, hit_start: NONE, cancel: 40, flags: &[(40, 0x1e0)] }] },
    Action { id: 0xcd, loop_from: 255, items: &[Item { frames: 64, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xce, loop_from: 255, items: &[Item { frames: 90, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd2, loop_from: 255, items: &[Item { frames: 27, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd3, loop_from: 255, items: &[Item { frames: 25, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd4, loop_from: 255, items: &[Item { frames: 40, speed: 48, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd5, loop_from: 255, items: &[Item { frames: 49, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd6, loop_from: 255, items: &[Item { frames: 61, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd7, loop_from: 255, items: &[Item { frames: 25, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd8, loop_from: 255, items: &[Item { frames: 25, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xd9, loop_from: 255, items: &[Item { frames: 45, speed: 64, b3: 4, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xdc, loop_from: 255, items: &[Item { frames: 45, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xdd, loop_from: 255, items: &[Item { frames: 22, speed: 48, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 58, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xe1, loop_from: 255, items: &[Item { frames: 45, speed: 64, b3: 0, hit_start: 25, cancel: 45, flags: &[(25, 0x1), (45, 0x1a0)] },
        Item { frames: 50, speed: 64, b3: 0, hit_start: NONE, cancel: 50, flags: &[(50, 0x1a0)] }] },
    Action { id: 0xe2, loop_from: 255, items: &[Item { frames: 50, speed: 64, b3: 0, hit_start: NONE, cancel: 50, flags: &[(50, 0x1a0)] }] },
    Action { id: 0xe3, loop_from: 255, items: &[Item { frames: 45, speed: 64, b3: 0, hit_start: 25, cancel: 45, flags: &[(25, 0x1), (45, 0x1a0)] },
        Item { frames: 50, speed: 64, b3: 0, hit_start: NONE, cancel: 50, flags: &[(50, 0x1a0)] }] },
    Action { id: 0xe6, loop_from: 255, items: &[Item { frames: 20, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xe7, loop_from: 255, items: &[Item { frames: 346, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xe8, loop_from: 255, items: &[Item { frames: 214, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[(81, 0x4000)] }] },
    Action { id: 0xe9, loop_from: 255, items: &[Item { frames: 60, speed: 64, b3: 2, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xea, loop_from: 255, items: &[Item { frames: 250, speed: 128, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xeb, loop_from: 255, items: &[Item { frames: 109, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xec, loop_from: 255, items: &[Item { frames: 293, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xf8, loop_from: 255, items: &[Item { frames: 34, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xf9, loop_from: 255, items: &[Item { frames: 16, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xfa, loop_from: 255, items: &[Item { frames: 71, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xfb, loop_from: 255, items: &[Item { frames: 94, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xfc, loop_from: 0, items: &[Item { frames: 11, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xfd, loop_from: 255, items: &[Item { frames: 57, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xfe, loop_from: 255, items: &[Item { frames: 30, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0xff, loop_from: 255, items: &[Item { frames: 59, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x100, loop_from: 255, items: &[Item { frames: 137, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x101, loop_from: 255, items: &[Item { frames: 102, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x102, loop_from: 255, items: &[Item { frames: 38, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x103, loop_from: 255, items: &[Item { frames: 35, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x104, loop_from: 255, items: &[Item { frames: 183, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x105, loop_from: 0, items: &[Item { frames: 120, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x106, loop_from: 255, items: &[Item { frames: 65, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x107, loop_from: 255, items: &[Item { frames: 79, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x108, loop_from: 255, items: &[Item { frames: 50, speed: 64, b3: 0, hit_start: 50, cancel: 50, flags: &[(50, 0x1a0), (50, 0x1)] }] },
    Action { id: 0x109, loop_from: 255, items: &[Item { frames: 45, speed: 64, b3: 0, hit_start: 25, cancel: 45, flags: &[(25, 0x1), (45, 0x1a0)] },
        Item { frames: 50, speed: 64, b3: 0, hit_start: NONE, cancel: 50, flags: &[(50, 0x1a0)] }] },
    Action { id: 0x10a, loop_from: 255, items: &[Item { frames: 45, speed: 64, b3: 0, hit_start: NONE, cancel: 13, flags: &[(13, 0x1a0)] }] },
    Action { id: 0x10b, loop_from: 255, items: &[Item { frames: 35, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x10c, loop_from: 255, items: &[Item { frames: 67, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x10d, loop_from: 255, items: &[Item { frames: 45, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 67, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x10e, loop_from: 255, items: &[Item { frames: 157, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x10f, loop_from: 255, items: &[Item { frames: 90, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x110, loop_from: 255, items: &[Item { frames: 89, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x111, loop_from: 255, items: &[Item { frames: 80, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x112, loop_from: 255, items: &[Item { frames: 174, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x113, loop_from: 255, items: &[Item { frames: 151, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[(126, 0x4000)] }] },
    Action { id: 0x114, loop_from: 255, items: &[Item { frames: 82, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 44, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x115, loop_from: 255, items: &[Item { frames: 31, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x119, loop_from: 255, items: &[Item { frames: 79, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x11a, loop_from: 255, items: &[Item { frames: 268, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x11c, loop_from: 255, items: &[Item { frames: 149, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x11e, loop_from: 255, items: &[Item { frames: 76, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[(70, 0x4000)] }] },
    Action { id: 0x123, loop_from: 255, items: &[Item { frames: 79, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x124, loop_from: 255, items: &[Item { frames: 268, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x126, loop_from: 255, items: &[Item { frames: 149, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x128, loop_from: 255, items: &[Item { frames: 76, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[(70, 0x4000)] }] },
    Action { id: 0x12c, loop_from: 255, items: &[Item { frames: 109, speed: 64, b3: 2, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x12d, loop_from: 255, items: &[Item { frames: 164, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x12e, loop_from: 255, items: &[Item { frames: 148, speed: 64, b3: 64, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 117, speed: 64, b3: 64, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x12f, loop_from: 255, items: &[Item { frames: 190, speed: 64, b3: 64, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x131, loop_from: 255, items: &[Item { frames: 50, speed: 64, b3: 2, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x132, loop_from: 255, items: &[Item { frames: 234, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x133, loop_from: 255, items: &[Item { frames: 152, speed: 64, b3: 64, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x134, loop_from: 255, items: &[Item { frames: 190, speed: 64, b3: 64, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x136, loop_from: 255, items: &[Item { frames: 172, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x137, loop_from: 255, items: &[Item { frames: 137, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x138, loop_from: 255, items: &[Item { frames: 298, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[(199, 0x4000)] }] },
    Action { id: 0x139, loop_from: 255, items: &[Item { frames: 98, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x13b, loop_from: 255, items: &[Item { frames: 88, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x13c, loop_from: 255, items: &[Item { frames: 235, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x13d, loop_from: 255, items: &[Item { frames: 100, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x13e, loop_from: 1, items: &[Item { frames: 190, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 30, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x140, loop_from: 255, items: &[Item { frames: 82, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 62, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x141, loop_from: 255, items: &[Item { frames: 51, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 39, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x142, loop_from: 255, items: &[Item { frames: 82, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 62, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x143, loop_from: 255, items: &[Item { frames: 427, speed: 254, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x145, loop_from: 255, items: &[Item { frames: 109, speed: 64, b3: 2, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x146, loop_from: 255, items: &[Item { frames: 164, speed: 64, b3: 0, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x147, loop_from: 255, items: &[Item { frames: 148, speed: 64, b3: 64, hit_start: NONE, cancel: NONE, flags: &[] },
        Item { frames: 117, speed: 64, b3: 64, hit_start: NONE, cancel: NONE, flags: &[] }] },
    Action { id: 0x148, loop_from: 255, items: &[Item { frames: 190, speed: 64, b3: 64, hit_start: NONE, cancel: NONE, flags: &[] }] },
];

/// (from action, from item, to action, flags, blend) -- `fn@0x00946a30` lookup table; blend is the byte at entry+3 (frames, [L] unit).
pub static TRANSITIONS: &[(u16, u8, u16, u8, u8)] = &[
    (0x0, 0, 0x0, 0x30, 30), (0x0, 0, 0xc, 0x20, 10), (0x0, 0, 0xd, 0x20, 10), (0x0, 0, 0x10, 0x20, 10),
    (0x0, 0, 0x11, 0x20, 10), (0x1, 0, 0x1, 0x30, 10), (0x3, 0, 0x3, 0x30, 40), (0x4, 0, 0x4, 0x30, 15),
    (0x4, 1, 0x0, 0x20, 0), (0x5, 0, 0x0, 0x20, 10), (0x5, 0, 0x5, 0x30, 15), (0x5, 1, 0x0, 0x20, 0),
    (0x6, 0, 0x0, 0x28, 15), (0x6, 0, 0x6, 0x30, 20), (0x6, 0, 0xc, 0x20, 40), (0x6, 0, 0xd, 0x20, 40),
    (0x6, 0, 0x10, 0x20, 40), (0x6, 0, 0x11, 0x20, 40), (0x6, 0, 0x24, 0x70, 10), (0x7, 0, 0x0, 0x28, 15),
    (0x7, 0, 0x7, 0x30, 20), (0x7, 0, 0xc, 0x20, 40), (0x7, 0, 0xd, 0x20, 40), (0x7, 0, 0x10, 0x20, 40),
    (0x7, 0, 0x11, 0x20, 40), (0x7, 0, 0x25, 0x70, 10), (0x8, 0, 0x8, 0x30, 10), (0xa, 0, 0xa, 0x30, 15),
    (0xa, 0, 0xb, 0x21, 15), (0xa, 0, 0xc, 0x21, 15), (0xa, 0, 0xd, 0x21, 15), (0xa, 0, 0x10, 0x21, 15),
    (0xa, 0, 0x11, 0x21, 15), (0xb, 0, 0xa, 0x21, 15), (0xb, 0, 0xb, 0x30, 15), (0xb, 0, 0xc, 0x21, 15),
    (0xb, 0, 0xd, 0x21, 15), (0xb, 0, 0x10, 0x21, 15), (0xb, 0, 0x11, 0x21, 15), (0xc, 0, 0xa, 0x21, 15),
    (0xc, 0, 0xb, 0x21, 15), (0xc, 0, 0xc, 0x30, 60), (0xc, 0, 0xd, 0x21, 15), (0xc, 0, 0x10, 0x21, 20),
    (0xc, 0, 0x11, 0x21, 20), (0xc, 0, 0x12, 0x21, 60), (0xc, 0, 0x13, 0x21, 60), (0xd, 0, 0xa, 0x21, 15),
    (0xd, 0, 0xb, 0x21, 15), (0xd, 0, 0xc, 0x21, 15), (0xd, 0, 0xd, 0x30, 60), (0xd, 0, 0x10, 0x21, 20),
    (0xd, 0, 0x11, 0x21, 20), (0xd, 0, 0x12, 0x21, 60), (0xd, 0, 0x13, 0x21, 60), (0xe, 0, 0x0, 0x20, 0),
    (0xe, 0, 0xe, 0x30, 20), (0x10, 0, 0xa, 0x21, 15), (0x10, 0, 0xb, 0x21, 15), (0x10, 0, 0xc, 0x21, 20),
    (0x10, 0, 0xd, 0x21, 20), (0x10, 0, 0x10, 0x30, 60), (0x10, 0, 0x11, 0x21, 15), (0x11, 0, 0xa, 0x21, 15),
    (0x11, 0, 0xb, 0x21, 15), (0x11, 0, 0xc, 0x21, 20), (0x11, 0, 0xd, 0x21, 20), (0x11, 0, 0x10, 0x21, 15),
    (0x11, 0, 0x11, 0x30, 60), (0x12, 0, 0x12, 0x30, 60), (0x13, 0, 0x13, 0x30, 60), (0x14, 0, 0x0, 0x20, 0),
    (0x14, 0, 0x14, 0x30, 20), (0x16, 0, 0x16, 0x30, 15), (0x16, 0, 0x18, 0x30, 10), (0x17, 0, 0x17, 0x30, 20),
    (0x19, 0, 0x19, 0x30, 20), (0x1b, 0, 0x0, 0x20, 0), (0x1b, 0, 0x1b, 0x30, 20), (0x1c, 0, 0x0, 0x20, 0),
    (0x1c, 0, 0xa, 0x20, 15), (0x1c, 0, 0xb, 0x20, 15), (0x1c, 0, 0xc, 0x20, 15), (0x1c, 0, 0xd, 0x20, 15),
    (0x1d, 0, 0x0, 0x20, 40), (0x1d, 0, 0x1f, 0x20, 0), (0x1e, 0, 0x0, 0x20, 0), (0x1f, 0, 0x0, 0x20, 0),
    (0x1f, 0, 0x1f, 0x30, 15), (0x21, 0, 0x21, 0x60, 15), (0x22, 0, 0x22, 0x60, 15), (0x27, 0, 0x0, 0x20, 15),
    (0x27, 0, 0x27, 0x30, 10), (0x28, 0, 0x28, 0x30, 10), (0x28, 1, 0x0, 0x20, 0), (0x29, 0, 0x29, 0x30, 10),
    (0x29, 0, 0x37, 0x30, 6), (0x29, 1, 0x0, 0x20, 0), (0x2a, 0, 0x2a, 0x30, 10), (0x2a, 1, 0x0, 0x20, 0),
    (0x2b, 0, 0x2b, 0x30, 10), (0x2b, 1, 0x0, 0x20, 0), (0x2c, 0, 0x2c, 0x30, 10), (0x2c, 1, 0x0, 0x20, 10),
    (0x2d, 0, 0x2d, 0x30, 10), (0x2d, 1, 0x0, 0x20, 10), (0x2e, 0, 0x2e, 0x30, 10), (0x2e, 1, 0x0, 0x20, 10),
    (0x2f, 0, 0x2f, 0x30, 10), (0x2f, 1, 0x0, 0x20, 10), (0x32, 0, 0x32, 0x30, 4), (0x33, 0, 0x33, 0x30, 4),
    (0x34, 0, 0x0, 0x60, 15), (0x34, 0, 0x34, 0x30, 15), (0x35, 0, 0x0, 0x60, 15), (0x35, 0, 0xa, 0x20, 60),
    (0x35, 0, 0xb, 0x20, 0), (0x35, 0, 0x35, 0x30, 15), (0x38, 0, 0x38, 0x30, 90), (0x39, 0, 0x39, 0x30, 20),
    (0x3a, 0, 0x0, 0x20, 0), (0x3a, 0, 0x3a, 0x30, 15), (0x3b, 0, 0x3b, 0x30, 10), (0x3c, 0, 0x33, 0x30, 15),
    (0x3c, 0, 0x3c, 0x30, 15), (0x3d, 0, 0x3d, 0x30, 15), (0x3e, 0, 0x3e, 0x30, 15), (0x3f, 0, 0x0, 0x20, 0),
    (0x3f, 0, 0x3f, 0x30, 15), (0x40, 0, 0x40, 0x30, 200), (0x41, 0, 0x41, 0x30, 8), (0x42, 0, 0x42, 0x30, 15),
    (0x43, 0, 0x0, 0x28, 15), (0x43, 0, 0x5, 0x38, 15), (0x43, 0, 0xa, 0x38, 15), (0x43, 0, 0xb, 0x38, 15),
    (0x43, 0, 0xc, 0x38, 15), (0x43, 0, 0xd, 0x38, 15), (0x43, 0, 0xe, 0x38, 15), (0x43, 0, 0xf, 0x38, 15),
    (0x43, 0, 0x10, 0x38, 15), (0x43, 0, 0x11, 0x38, 15), (0x43, 0, 0x12, 0x30, 6), (0x43, 0, 0x43, 0x30, 15),
    (0x44, 0, 0x0, 0x28, 15), (0x44, 0, 0x5, 0x38, 15), (0x44, 0, 0xa, 0x38, 15), (0x44, 0, 0xb, 0x38, 15),
    (0x44, 0, 0xc, 0x38, 15), (0x44, 0, 0xd, 0x38, 15), (0x44, 0, 0xe, 0x38, 15), (0x44, 0, 0xf, 0x38, 15),
    (0x44, 0, 0x10, 0x38, 15), (0x44, 0, 0x11, 0x38, 15), (0x44, 0, 0x44, 0x30, 15), (0x45, 0, 0x0, 0x28, 15),
    (0x45, 0, 0x5, 0x38, 15), (0x45, 0, 0xa, 0x38, 15), (0x45, 0, 0xb, 0x38, 15), (0x45, 0, 0xc, 0x28, 15),
    (0x45, 0, 0xd, 0x38, 15), (0x45, 0, 0xe, 0x38, 15), (0x45, 0, 0xf, 0x38, 15), (0x45, 0, 0x10, 0x38, 15),
    (0x45, 0, 0x11, 0x38, 15), (0x45, 0, 0x45, 0x30, 45), (0x46, 0, 0x46, 0x30, 15), (0x46, 0, 0x82, 0x20, 0),
    (0x46, 0, 0x83, 0x20, 0), (0x46, 0, 0x84, 0x20, 0), (0x47, 0, 0x47, 0x30, 6), (0x48, 0, 0x48, 0x30, 6),
    (0x4b, 0, 0x4b, 0x30, 10), (0x4c, 0, 0x4c, 0x30, 10), (0x4d, 0, 0x4d, 0x30, 60), (0x4e, 0, 0x4e, 0x30, 20),
    (0x4f, 0, 0x4f, 0x30, 90), (0x50, 0, 0x50, 0x30, 6), (0x50, 0, 0x51, 0x20, 6), (0x51, 0, 0x51, 0x30, 15),
    (0x52, 0, 0x52, 0x30, 6), (0x53, 0, 0x53, 0x30, 90), (0x54, 0, 0x54, 0x30, 6), (0x55, 0, 0x55, 0x30, 90),
    (0x56, 0, 0x56, 0x30, 6), (0x57, 0, 0x57, 0x30, 140), (0x57, 0, 0x59, 0x30, 15), (0x57, 0, 0x5b, 0x30, 15),
    (0x58, 0, 0x58, 0x30, 6), (0x59, 0, 0x57, 0x30, 140), (0x59, 0, 0x59, 0x30, 15), (0x59, 0, 0x5b, 0x30, 15),
    (0x5a, 0, 0x5a, 0x30, 6), (0x5b, 0, 0x57, 0x30, 140), (0x5b, 0, 0x59, 0x30, 15), (0x5b, 0, 0x5b, 0x30, 15),
    (0x5c, 0, 0x5c, 0x30, 6), (0x5d, 0, 0x5d, 0x30, 90), (0x5e, 1, 0x0, 0x20, 10), (0x5f, 0, 0x45, 0x30, 15),
    (0x5f, 0, 0x5f, 0x30, 90), (0x60, 0, 0x60, 0x30, 10), (0x62, 0, 0x0, 0x20, 15), (0x62, 0, 0x62, 0x30, 10),
    (0x63, 0, 0x63, 0x30, 20), (0x64, 0, 0x64, 0x30, 15), (0x65, 0, 0x64, 0x20, 70), (0x65, 0, 0x65, 0x30, 70),
    (0x66, 0, 0x64, 0x20, 70), (0x66, 0, 0x66, 0x30, 70), (0x67, 0, 0x67, 0x30, 15), (0x68, 0, 0x68, 0x30, 15),
    (0x6b, 0, 0x6b, 0x30, 15), (0x6c, 0, 0x6c, 0x30, 15), (0x80, 0, 0x80, 0x30, 3), (0x81, 0, 0x81, 0x30, 15),
    (0x82, 0, 0x3d, 0x20, 100), (0x82, 0, 0x82, 0x30, 30), (0x82, 0, 0x83, 0x20, 15), (0x83, 0, 0x3d, 0x20, 100),
    (0x83, 0, 0x82, 0x20, 15), (0x83, 0, 0x83, 0x30, 30), (0x84, 0, 0x3d, 0x20, 100), (0x84, 0, 0x84, 0x30, 15),
    (0x85, 0, 0x85, 0x30, 30), (0x86, 0, 0x86, 0x30, 10), (0x87, 0, 0x87, 0x30, 10), (0x88, 0, 0x82, 0x20, 15),
    (0x88, 0, 0x83, 0x20, 15), (0x88, 0, 0x88, 0x30, 20), (0x89, 0, 0x89, 0x30, 10), (0x8a, 0, 0x8a, 0x30, 10),
    (0x8b, 0, 0x8b, 0x30, 10), (0x8c, 0, 0x8c, 0x30, 10), (0x8e, 0, 0x8e, 0x30, 30), (0x8f, 0, 0x3e, 0x60, 30),
    (0x8f, 0, 0x8e, 0x60, 30), (0x8f, 0, 0x8f, 0x30, 8), (0x8f, 0, 0x93, 0x60, 30), (0x8f, 0, 0x94, 0x60, 30),
    (0x90, 0, 0x8f, 0x20, 0), (0x90, 0, 0x90, 0x30, 0), (0x91, 0, 0x3e, 0x60, 30), (0x91, 0, 0x8e, 0x60, 30),
    (0x91, 0, 0x91, 0x30, 10), (0x91, 0, 0x93, 0x60, 30), (0x91, 0, 0x94, 0x60, 30), (0x92, 0, 0x3e, 0x60, 30),
    (0x92, 0, 0x8e, 0x60, 30), (0x92, 0, 0x92, 0x30, 10), (0x92, 0, 0x93, 0x60, 30), (0x92, 0, 0x94, 0x60, 30),
    (0x93, 0, 0x93, 0x30, 150), (0x94, 0, 0x94, 0x30, 150), (0x96, 0, 0x0, 0x20, 30), (0x96, 0, 0xa, 0x20, 30),
    (0x96, 0, 0xb, 0x20, 30), (0x96, 0, 0xc, 0x20, 30), (0x96, 0, 0xd, 0x20, 30), (0x96, 0, 0xe, 0x20, 30),
    (0x96, 0, 0xf, 0x20, 30), (0x96, 0, 0x10, 0x20, 30), (0x96, 0, 0x11, 0x20, 30), (0x96, 0, 0x96, 0x30, 20),
    (0x96, 0, 0xbf, 0x20, 6), (0x97, 0, 0x0, 0x20, 30), (0x97, 0, 0xa, 0x20, 30), (0x97, 0, 0xb, 0x20, 30),
    (0x97, 0, 0xc, 0x20, 30), (0x97, 0, 0xd, 0x20, 30), (0x97, 0, 0xe, 0x20, 30), (0x97, 0, 0xf, 0x20, 30),
    (0x97, 0, 0x10, 0x20, 30), (0x97, 0, 0x11, 0x20, 30), (0x97, 0, 0x97, 0x30, 20), (0x98, 0, 0x98, 0x30, 10),
    (0x99, 0, 0x0, 0x20, 0), (0x99, 0, 0x99, 0x30, 20), (0x9b, 0, 0x0, 0x20, 0), (0x9b, 0, 0x9b, 0x30, 20),
    (0xa2, 0, 0xa2, 0x30, 10), (0xa4, 0, 0xa4, 0x30, 15), (0xa5, 0, 0xa5, 0x30, 15), (0xa6, 0, 0xa6, 0x30, 30),
    (0xa7, 0, 0xa7, 0x30, 30), (0xa8, 0, 0xa8, 0x30, 15), (0xa8, 1, 0x0, 0x60, 15), (0xaa, 0, 0xaa, 0x20, 20),
    (0xab, 0, 0x0, 0x20, 15), (0xab, 0, 0xab, 0x30, 20), (0xac, 0, 0xac, 0x30, 20), (0xac, 1, 0x0, 0x20, 15),
    (0xad, 0, 0x0, 0x20, 60), (0xad, 0, 0xad, 0x30, 15), (0xad, 0, 0xb1, 0x30, 15), (0xb1, 0, 0x0, 0x20, 60),
    (0xb1, 0, 0xad, 0x30, 15), (0xb1, 0, 0xb1, 0x30, 15), (0xb2, 0, 0xb2, 0x30, 15), (0xb3, 0, 0xb3, 0x30, 10),
    (0xb4, 0, 0xb4, 0x30, 10), (0xb5, 0, 0xb5, 0x20, 10), (0xb6, 0, 0xb6, 0x20, 10), (0xbe, 0, 0xbe, 0x30, 30),
    (0xbe, 0, 0xc6, 0x20, 0), (0xbf, 0, 0xbf, 0x30, 30), (0xbf, 0, 0xc6, 0x20, 0), (0xc0, 0, 0xc0, 0x30, 30),
    (0xc0, 0, 0xc6, 0x20, 0), (0xc1, 0, 0xc1, 0x30, 30), (0xc1, 0, 0xc6, 0x20, 0), (0xc2, 0, 0xc2, 0x30, 10),
    (0xc2, 0, 0xc4, 0x20, 10), (0xc2, 0, 0xc6, 0x20, 10), (0xc3, 0, 0xc6, 0x20, 10), (0xc4, 0, 0xc2, 0x20, 10),
    (0xc4, 0, 0xc4, 0x30, 10), (0xc4, 0, 0xc6, 0x20, 10), (0xc5, 0, 0xc6, 0x20, 10), (0xc6, 0, 0xbe, 0x20, 10),
    (0xc6, 0, 0xbf, 0x20, 10), (0xc6, 0, 0xc0, 0x20, 10), (0xc6, 0, 0xc1, 0x20, 10), (0xc6, 0, 0xc2, 0x20, 10),
    (0xc6, 0, 0xc4, 0x20, 10), (0xc7, 0, 0xc6, 0x20, 10), (0xc8, 0, 0xc6, 0x20, 10), (0xc9, 0, 0xc6, 0x20, 10),
    (0xca, 0, 0xc6, 0x20, 10), (0xcd, 0, 0x0, 0x20, 0), (0xcd, 0, 0xcd, 0x30, 30), (0xce, 0, 0xce, 0x30, 20),
    (0xd2, 0, 0xd2, 0x30, 15), (0xd2, 0, 0xd4, 0x20, 20), (0xd3, 0, 0xd3, 0x30, 15), (0xd4, 0, 0x0, 0x60, 0),
    (0xd4, 0, 0xd4, 0x30, 8), (0xd5, 0, 0x0, 0x20, 0), (0xd5, 0, 0xd5, 0x30, 8), (0xd6, 0, 0xd6, 0x30, 6),
    (0xd7, 0, 0xd7, 0x30, 4), (0xd8, 0, 0xd8, 0x30, 4), (0xdc, 0, 0xdc, 0x30, 15), (0xdd, 0, 0xdd, 0x30, 20),
    (0xe1, 0, 0xe1, 0x30, 15), (0xe2, 0, 0xe2, 0x30, 15), (0xe3, 0, 0xe3, 0x30, 15), (0xe6, 0, 0xe6, 0x30, 15),
    (0xe7, 0, 0xe7, 0x30, 10), (0xe9, 0, 0xe9, 0x30, 15), (0xeb, 0, 0xeb, 0x30, 15), (0xec, 0, 0xec, 0x30, 15),
    (0xfa, 0, 0xfa, 0x30, 10), (0xfb, 0, 0xfb, 0x30, 0), (0xfc, 0, 0xfc, 0x30, 0), (0xfd, 0, 0xfd, 0x30, 5),
    (0xfe, 0, 0xfe, 0x30, 0), (0xff, 0, 0xff, 0x30, 15), (0x101, 0, 0x0, 0x20, 10), (0x101, 0, 0x101, 0x30, 10),
    (0x102, 0, 0x0, 0x20, 10), (0x102, 0, 0x102, 0x30, 15), (0x103, 0, 0x103, 0x30, 10), (0x104, 0, 0x104, 0x30, 20),
    (0x105, 0, 0x105, 0x30, 15), (0x106, 0, 0x106, 0x30, 10), (0x107, 0, 0x107, 0x30, 10), (0x108, 0, 0x106, 0x20, 30),
    (0x108, 0, 0x107, 0x20, 30), (0x108, 0, 0x108, 0x30, 15), (0x109, 0, 0x106, 0x20, 30), (0x109, 0, 0x107, 0x20, 30),
    (0x109, 0, 0x109, 0x30, 15), (0x10a, 0, 0x106, 0x20, 30), (0x10a, 0, 0x107, 0x20, 30), (0x10b, 0, 0x10b, 0x30, 10),
    (0x10c, 0, 0x10c, 0x30, 15), (0x10d, 0, 0x10d, 0x30, 15), (0x10e, 0, 0x10e, 0x30, 20), (0x10f, 0, 0x10f, 0x10, 15),
    (0x110, 0, 0x110, 0x30, 10), (0x111, 0, 0x111, 0x30, 15), (0x114, 1, 0x0, 0x20, 0), (0x11c, 0, 0x11c, 0x30, 20),
    (0x11e, 0, 0x11e, 0x30, 15), (0x126, 0, 0x126, 0x30, 20), (0x128, 0, 0x128, 0x30, 15), (0x12c, 0, 0x12c, 0x30, 15),
    (0x12e, 0, 0x12e, 0x30, 15), (0x12e, 1, 0x12e, 0x20, 10), (0x12f, 0, 0x12f, 0x30, 15), (0x131, 0, 0x131, 0x30, 15),
    (0x133, 0, 0x133, 0x30, 15), (0x134, 0, 0x134, 0x30, 15), (0x137, 0, 0x137, 0x30, 15), (0x139, 0, 0x139, 0x30, 15),
    (0x13b, 0, 0x13b, 0x30, 15), (0x13c, 0, 0x13c, 0x30, 15), (0x13d, 0, 0xbf, 0x20, 90), (0x140, 0, 0x140, 0x30, 15),
    (0x140, 1, 0x0, 0x20, 0), (0x141, 0, 0x141, 0x30, 15), (0x141, 1, 0x0, 0x20, 0), (0x142, 0, 0x142, 0x30, 15),
    (0x142, 1, 0x0, 0x20, 0), (0x143, 0, 0x143, 0x30, 15), (0x145, 0, 0x145, 0x60, 15), (0x147, 0, 0x147, 0x60, 15),
    (0x147, 1, 0x147, 0x20, 10), (0x148, 0, 0x148, 0x60, 15),
];
