#!/usr/bin/env python3
"""Mechanics ledger tool.

  python3 tools/ledger.py status            # print a summary table per group
  python3 tools/ledger.py render            # rewrite spec/STATUS.md from spec/mechanics.yaml
  python3 tools/ledger.py show J05          # print one mechanic
  python3 tools/ledger.py next [GROUP]      # list NOT_STARTED / RESEARCHED mechanics to pick up
  python3 tools/ledger.py set J05 status=RESEARCHED evidence=REQUIRES_BINARY_VERIFICATION \
          binary+=CM_Cam@0x45b1b0 doc=spec/evidence/J05.md notes="..."
  python3 tools/ledger.py check            # validate the file (ids unique, enums valid, docs exist)

Rules (also in docs/PLAYBOOK.md):
  * status goes NOT_STARTED -> RESEARCHED (findings doc written) -> PARTIAL/IMPLEMENTED (Rust
    exists) -> VERIFIED (a test reproduces a value or behaviour recovered from the binary/data).
  * `binary` entries are `FunctionName@0xaddr` in KingKong8.exe (PC) unless prefixed `ps2:`.
  * `data` entries name game data (ova/ofc statements, level banks, GAO names).
  * every mechanic that is RESEARCHED or beyond must have `doc` pointing at spec/evidence/<ID>.md.
"""
import sys, os, yaml
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(ROOT, "spec", "mechanics.yaml")

def load():
    return yaml.safe_load(open(PATH, encoding="utf-8"))

def save(d):
    yaml.safe_dump(d, open(PATH, "w", encoding="utf-8"), sort_keys=False, allow_unicode=True, width=120)

def all_mechs(d):
    for g in d["groups"]:
        for m in g["mechanics"]:
            yield g, m

def find(d, mid):
    for g, m in all_mechs(d):
        if m["id"] == mid:
            return g, m
    sys.exit("unknown mechanic id %s" % mid)

def status(d):
    cols = d["statuses"]
    print("%-24s %5s " % ("group", "total") + " ".join("%12s" % c for c in cols))
    tot = {c: 0 for c in cols}
    for g in d["groups"]:
        cnt = {c: 0 for c in cols}
        for m in g["mechanics"]:
            cnt[m["status"]] += 1; tot[m["status"]] += 1
        print("%-24s %5d " % (g["id"], len(g["mechanics"])) + " ".join("%12d" % cnt[c] for c in cols))
    print("%-24s %5d " % ("ALL", sum(tot.values())) + " ".join("%12d" % tot[c] for c in cols))

def render(d):
    out = ["# Mechanics status (generated by tools/ledger.py render; do not edit by hand)", ""]
    out.append("| Group | Total | " + " | ".join(d["statuses"]) + " |")
    out.append("|---|---|" + "|".join("---" for _ in d["statuses"]) + "|")
    for g in d["groups"]:
        cnt = {c: 0 for c in d["statuses"]}
        for m in g["mechanics"]:
            cnt[m["status"]] += 1
        out.append("| %s | %d | %s |" % (g["id"], len(g["mechanics"]), " | ".join(str(cnt[c]) for c in d["statuses"])))
    out.append("")
    for g in d["groups"]:
        out.append("## %s: %s" % (g["id"], g["title"]))
        out.append("")
        out.append("| ID | Mechanic | Status | Evidence | Binary | Rust | Doc | Notes |")
        out.append("|---|---|---|---|---|---|---|---|")
        for m in g["mechanics"]:
            doc = ("[%s](../%s)" % (m["doc"], m["doc"])) if m.get("doc") else ""
            out.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (
                m["id"], m["name"], m["status"], m["evidence"],
                "<br>".join(m.get("binary") or []), "<br>".join(m.get("rust") or []), doc,
                (m.get("notes") or "").replace("|", "/")))
        out.append("")
    open(os.path.join(ROOT, "spec", "STATUS.md"), "w", encoding="utf-8").write("\n".join(out))
    print("wrote spec/STATUS.md")

def check(d):
    ids = set(); bad = 0
    for g, m in all_mechs(d):
        if m["id"] in ids:
            print("duplicate id", m["id"]); bad += 1
        ids.add(m["id"])
        if m["status"] not in d["statuses"]:
            print(m["id"], "bad status", m["status"]); bad += 1
        if m["evidence"] not in d["evidence_levels"]:
            print(m["id"], "bad evidence", m["evidence"]); bad += 1
        if m["status"] != "NOT_STARTED" and m.get("doc") and not os.path.exists(os.path.join(ROOT, m["doc"])):
            print(m["id"], "doc missing:", m["doc"]); bad += 1
        if m["status"] in ("RESEARCHED", "VERIFIED") and not m.get("doc"):
            print(m["id"], "status", m["status"], "needs a doc"); bad += 1
    print("checked %d mechanics, %d problems" % (len(ids), bad))
    return bad

def main():
    if len(sys.argv) < 2:
        print(__doc__); return
    d = load(); cmd = sys.argv[1]
    if cmd == "status": status(d)
    elif cmd == "render": render(d)
    elif cmd == "check": sys.exit(1 if check(d) else 0)
    elif cmd == "show":
        g, m = find(d, sys.argv[2]); print(yaml.safe_dump(m, sort_keys=False, allow_unicode=True))
    elif cmd == "next":
        grp = sys.argv[2] if len(sys.argv) > 2 else None
        for g, m in all_mechs(d):
            if grp and g["id"] != grp: continue
            if m["status"] in ("NOT_STARTED", "RESEARCHED"):
                print("%-5s %-12s %-28s %s" % (m["id"], m["status"], m["name"], m["behavior"]))
    elif cmd == "set":
        g, m = find(d, sys.argv[2])
        for kv in sys.argv[3:]:
            if "+=" in kv:
                k, v = kv.split("+=", 1); m.setdefault(k, []); m[k] = (m[k] or []) + [v]
            else:
                k, v = kv.split("=", 1); m[k] = v
        save(d); render(d); print(yaml.safe_dump(m, sort_keys=False, allow_unicode=True))
    else:
        print(__doc__)

if __name__ == "__main__":
    main()
